### ISSUE TITLE
There is a problem reading the wordnet_superset.txt 

### ISSUE THREAD

**Issue by Thoye** [catcd/RbSP#1]
File "/home/mrc/RbSP-master/utils.py", line 59, in load_wordnet_superset
    word, vec = line.strip().split('\t', 1)
ValueError: not enough values to unpack (expected 2, got 1)

There is a hyperlink ‘https://git-lfs.github.com/spec/v1’  in wordnet_superset.txt. Do you need to download it first?

**Comment by catcd** [comment]
We stored this file with Git LFS, if you cannot clone it with our project, should you download it separately and put it in /data/knowledge_base.
Or you can download it here.
[wordnet_superset.zip](https://github.com/catcd/RbSP/files/4439252/wordnet_superset.zip)
